baseURL = "https://vegai.fi"
languageCode = "en-us"
title = "vegai.fi"
theme = "basics"

[params]
author = ""

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4
